#pragma autorecover

#pragma namespace ("\\\\.\\root\\CIMv2")
class CIM_ComputerSystem
{
    [key]
    string   Name;
    uint16   AdminPasswordStatus;
    boolean  AutomaticManagedPagefile;
    boolean  AutomaticResetBootOption;
    boolean  AutomaticResetCapability;
    uint16   BootOptionOnLimit;
    uint16   BootOptionOnWatchDog;
    boolean  BootROMSupported;
    string   BootupState;
    uint16   BootStatus[];
    string   Caption;
    uint16   ChassisBootupState;
    string   ChassisSKUNumber;
    string   CreationClassName;
    sint16   CurrentTimeZone;
    boolean  DaylightInEffect;
    string   Description;
    string   DNSHostName;
    string   Domain;
    uint16   DomainRole;
    boolean  EnableDaylightSavingsTime;
    uint16   FrontPanelResetStatus;
    boolean  HypervisorPresent;
    boolean  InfraredSupported;
    string   InitialLoadInfo[];
    datetime InstallDate;
    uint16   KeyboardPasswordStatus;
    string   LastLoadInfo;
    string   Manufacturer;
    string   Model;
    string   NameFormat;
    boolean  NetworkServerModeEnabled;
    uint32   NumberOfLogicalProcessors;
    uint32   NumberOfProcessors;
    uint8    OEMLogoBitmap[];
    string   OEMStringArray[];
    boolean  PartOfDomain;
    sint64   PauseAfterReset;
    uint16   PCSystemType;
    uint16   PCSystemTypeEx;
    uint16   PowerManagementCapabilities[];
    boolean  PowerManagementSupported;
    uint16   PowerOnPasswordStatus;
    uint16   PowerState;
    uint16   PowerSupplyState;
    string   PrimaryOwnerContact;
    string   PrimaryOwnerName;
    uint16   ResetCapability;
    sint16   ResetCount;
    sint16   ResetLimit;
    string   Roles[];
    string   Status;
    string   SupportContactDescription[];
    string   SystemFamily;
    string   SystemSKUNumber;
    uint16   SystemStartupDelay;
    string   SystemStartupOptions[];
    uint8    SystemStartupSetting;
    string   SystemType;
    uint16   ThermalState;
    uint64   TotalPhysicalMemory;
    string   UserName;
    uint16   WakeUpType;
    string   Workgroup;
};

class Win32_ComputerSystem : CIM_ComputerSystem
{
};