#pragma autorecover

#pragma namespace ("\\\\.\\root\\CIMv2")
class Win32_ComputerSystem
{
    [key]
    string Domain;
    string Manufacturer;
    string Model;
    string Name;
    string PrimaryOwnerName;
    uint64 TotalPhysicalMemory;
};