#pragma autorecover

#pragma namespace ("\\\\.\\root\\CIMv2")
class Win32_DiskDrive
{
    [key]
    uint32 Partitions;
    string DeviceID;
    string Model;
    uint64 Size;
    String Caption;
};
