#pragma autorecover
#pragma namespace ("\\\\.\\Root\\CIMv2")
class Win32_PortConnector
{
    [key]
    string   Caption;
    string   ConnectorPinout;
    uint16   ConnectorType[];
    string   CreationClassName;
    string   Description;
    string   ExternalReferenceDesignator;
    datetime InstallDate;
    string   InternalReferenceDesignator;
    string   Manufacturer;
    string   Model;
    string   Name;
    string   OtherIdentifyingInfo;
    string   PartNumber;
    uint16   PortType;
    boolean  PoweredOn;
    string   SerialNumber;
    string   SKU;
    string   Status;
    string   Tag;
    string   Version;
};