#pragma autorecover

#pragma namespace ("\\\\.\\root\\CIMv2")
class Win32_SystemEnclosure
{
    [key]
    string Manufacturer;
    string Model;
    boolean LockPresent;
    string SerialNumber;
    string SMBIOSAssetTag;
    uint16 SecurityStatus;
};