#pragma autorecover
#pragma namespace ("\\\\.\\Root\\CIMv2")
class CIM_Memory
{
  [key]
  string   DeviceID;
  uint16   Access;
  uint8    AdditionalErrorData[];
  uint16   Availability; 
  uint64   BlockSize;
  string   Caption; 
  uint32   ConfigManagerErrorCode;
  boolean  ConfigManagerUserConfig;
  boolean  CorrectableError; 
  string   Description; 
  uint64   EndingAddress;
  uint16   ErrorAccess;
  uint64   ErrorAddress;
  boolean  ErrorCleared;
  uint8    ErrorData[]; 
  uint16   ErrorDataOrder;
  string   ErrorDescription; 
  uint16   ErrorInfo;
  string   ErrorMethodology; 
  uint64   ErrorResolution;
  datetime ErrorTime;
  uint32   ErrorTransferSize;
  datetime InstallDate; 
  uint32   LastErrorCode;
  string   Name; 
  uint64   NumberOfBlocks;
  string   OtherErrorDescription;
  string   PNPDeviceID; 
  uint16   PowerManagementCapabilities[];
  boolean  PowerManagementSupported; 
  string   Purpose;
  uint64   StartingAddress; 
  string   Status;
  uint16   StatusInfo;
  string   SystemCreationClassName;
  boolean  SystemLevelAddress;
  string   SystemName;
};
class CIM_CacheMemory : CIM_Memory
{
  uint16   Associativity;
  uint16   CacheType; 
  string   CreationClassName; 
  uint32   FlushTimer;
  uint16   Level; 
  uint32   LineSize; 
  uint16   ReadPolicy; 
  uint16   ReplacementPolicy; 
  uint16   WritePolicy; 
};
class Win32_CacheMemory : CIM_CacheMemory
{
  uint32   CacheSpeed; 
  uint16   CurrentSRAM[];  
  uint16   SupportedSRAM[]; 
  uint16   ErrorCorrectType; 
  uint16   Location; 
  uint32   MaxCacheSize; 
  uint32   InstalledSize;  
};