#pragma autorecover
#pragma namespace("\\\\.\\root\\CIMv2")
class CIM_PhysicalConnector
{
    [key]
    string   Tag;
    string   Caption;
    string   Description;
    datetime InstallDate;
    string   Name;
    string   Status;
    string   CreationClassName;
    string   Manufacturer;
    string   Model;
    string   OtherIdentifyingInfo;
    string   PartNumber;
    boolean  PoweredOn;
    string   SerialNumber;
    string   SKU;
    string   Version;
    string   ConnectorPinout;
    uint16   ConnectorType[];
};

class CIM_Slot : CIM_PhysicalConnector 
{
    real32   HeightAllowed;
    real32   LengthAllowed;
    uint16   MaxDataWidth;
    uint16   Number;
    string   PurposeDescription;
    boolean  SpecialPurpose;
    boolean  SupportsHotPlug;
    uint32   ThermalRating;
    boolean  PMESignal;
    string   SlotDesignation;
    boolean  Shared;
    uint32   FunctionNumber;
    uint32   DeviceNumber;
    uint32   SegmentGroupNumber;
    uint16   CurrentUsage;
    uint32   BusNumber;
    uint16   VccMixedVoltageSupport[];
    uint16   VppMixedVoltageSupport[];
};

class Win32_SystemSlot : CIM_Slot 
{
};