#pragma autorecover
#pragma namespace("\\\\.\\root\\wmi")

class MSAcpi_ThermalZoneTemperature 
{
    [key]
    string   InstanceName;
    boolean  Active;
    uint32   ActiveTripPoint[];
    uint32   ActiveTripPointCount;
    sint32   CriticalTripPoint;
    sint32   CurrentTemperature;
    uint32   PassiveTripPoint;
    uint32   Reserved;
    uint32   SamplingPeriod;
    sint32   ThermalConstant1;
    sint32   ThermalConstant2;
    uint32   ThermalStamp;
};