#pragma autorecover
#pragma namespace("\\\\.\\root\\CIMv2")

class Win32_SMBIOSMemory
{
    [key]
    string   DeviceID;
    uint16   Access;
    uint8    AdditionalErrorData[];
    uint16   Availability;
    uint64   BlockSize;
    string   Caption;
    uint32   ConfigManagerErrorCode;
    boolean  ConfigManagerUserConfig;
    boolean  CorrectableError;
    string   CreationClassName;
    string   Description;
    uint64   EndingAddress;
    uint16   ErrorAccess;
    uint64   ErrorAddress;
    boolean  ErrorCleared;
    uint8    ErrorData[];
    uint16   ErrorDataOrder;
    string   ErrorDescription;
    uint16   ErrorInfo;
    string   ErrorMethodology;
    uint64   ErrorResolution;
    datetime ErrorTime;
    uint32   ErrorTransferSize;
    datetime InstallDate;
    uint32   LastErrorCode;
    string   Name;
    uint64   NumberOfBlocks;
    string   OtherErrorDescription;
    string   PNPDeviceID;
    uint16   PowerManagementCapabilities[];
    boolean  PowerManagementSupported;
    string   Purpose;
    uint64   StartingAddress;
    string   Status;
    uint16e  StatusInfo;
    string   SystemCreationClassName;
    boolean  SystemLevelAddress;
    string   SystemName;
};

class Win32_MemoryArray : Win32_SMBIOSMemory
{
    uint16   ErrorGranularity;
};