#pragma autorecover
#pragma namespace ("\\\\.\\Root\\CIMv2")
class Win32_PerfFormattedData_Counters_ThermalZoneInformation 
{
    [key]
    string Name;
    string Caption;
    string Description;
    uint32 Frequency_Object;
    uint32 Frequency_PerfTime;
    uint32 Frequency_Sys100NS;
    sint32 HighPrecisionTemperature;
    sint32 Temperature;
    sint32 PercentPassiveLimit;
    uint32 ThrottleReasons;
    uint64 Timestamp_Object;
    uint64 Timestamp_PerfTime;
    uint64 Timestamp_Sys100NS;
};