- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
#  become: yes
  vars:
    vm_name: win10-analysis-vm
    vcpus: 2
    vm_memory: 16384
    cleanup: no
    net: default
    ssh_pub_key: "/root/.ssh/id_rsa.pub"
    qcow2_location: "/var/lib/libvirt/images"
    vm_os_variant: "win10"
    vm_network_name: "internal_network"
  
  tasks:
    - name: Create a directory to store .qcow2 file if it does not exist
        file:
          path: {{qcow2_location}}
          state: directory
          mode: '0755'

    - name: set a fact for referring to image throughout
      set_fact:
        IMAGE: "{{ qcow2_location }}/{{ vm_name }}.qcow2"

    - name: create a copy of the qcow2 image
      copy:
        src: "{{ qcow2_location }}/{{ qcow2.name }}"
        dest: "{{ IMAGE }}"
        remote_src: yes
 
    - name: Install KVM and related packages on Ubuntu
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
          - virt-viewer
        state: present
      when: ansible_os_family == "Debian"

    # - name: inject ssh key w/ virt-customize
    #   command: >
    #     virt-customize
    #     --add {{ IMAGE }}
    #     --ssh-inject root:string:"{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    #     --run-command 'chcon -R unconfined_u:object_r:ssh_home_t:s0 /root/.ssh/'
    # #    --selinux-relabel

    - name: use virt-install to import image
      become: yes
      command: >
        virt-install 
        --name {{ vm_name }}
        --vcpus={{vcpus}}
        --memory {{ vm_memory }}
        --os-variant {{ vm_os_variant }}
        --disk {{ IMAGE }},device=disk
        --import 
        --network network={{ vm_network_name }},model=virtio
        --vnc

    - name: wait for {{ vm_name }} to get an IP
      become: yes
      shell: >
        virsh domifaddr {{ vm_name }} | awk '/ipv4/ {split($NF,a,"/"); print a[1]}'
      register: IPinfo
      until: IPinfo.stdout != ""
      retries: 10
      delay: 5

     - name: use virt-install to import image
      become: yes
      shell: >
        virsh snapshot-create-as {{vm_name}} snapshot0 --description "snapshot0_master"     
        

    # - name: add this VM to a "allVMs" group for future plays
    #   add_host:
    #     name: "{{ vm_name }}"
    #     ansible_host: "{{ IPinfo.stdout }}"
    #     ansible_user: root
    #     ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    #     groups: allVMs

    # - name: output IPinfo
    #   debug:
    #     msg: "now you can perform the following: ssh root@{{ IPinfo.stdout }}"