---
#  Be sure to create a inventory.ini with [cape] and an IP for the cape server  
#  ansible-playbook -i inventory.ini playbook.yaml --ask-become-pass
- name: CAPE Deployment
  hosts: cape
  become: yes
  tasks:
    # - name: Install prerequisites for downloading keys
    #   apt:
    #     name:
    #       - gnupg
    #       - wget
    #     state: present
    # - name: Debug GPG key contents
    #   command: cat /tmp/RPM-GPG-KEY-mysql
    #   register: key_contents

    # - debug:
    #     var: key_contents.stdout

    - name: Update and install dependencies for git
      apt:
        name: git
        state: present
        force_apt_get: yes

    - name: Update and install dependencies for python3
      apt:
        name: python3
        state: present
        force_apt_get: yes        
    
    - name: Update and install dependencies for python3-pip
      apt:
        name: python3-pip
        state: present
        force_apt_get: yes      
      # apt:
        # update_cache: yes
        # name: "{{ item }}"
      # loop:
      #   - git
      #   - python3
      #   - python3-pip
    
    
    - name: Add CAPE directory as a safe Git directory
      command: git config --global --add safe.directory /opt/CAPEv2

    - name: Clone CAPE repository
      git:
        repo: https://github.com/kevoreilly/CAPEv2.git
        dest: /opt/CAPEv2

    - name: Install CAPE dependencies
      pip:
        requirements: /opt/CAPEv2/requirements.txt

    - name: Change to capesandbox directory
      command: chdir=/opt/CAPEv2 /bin/true 

    # Download the cape script and run
    # - name: Download CAPE installation script
    #   get_url:
    #     url: https://raw.githubusercontent.com/kevoreilly/CAPEv2/master/installer/cape2.sh
    #     dest: /opt/capesandbox/cape2.sh
    #     mode: '0755'
    - name: Copy CAPE installation script from local to remote
      copy:
        src: ./cape2.sh
        dest: /opt/CAPEv2/cape2.sh
        mode: '0755'
        
    - name: Run CAPE installation script with debug
      shell: yes "y" | sudo bash /opt/CAPEv2/cape2.sh base cape
      become: yes
      register: cape_install_output
      # command: sudo yes "y" | sudo bash /opt/CAPEv2/cape2.sh base cape
      # response:
        # ".*": 'y\r'
      # ignore_errors: yes      
      # ansible.builtin.script: 
      # ansible.builtin.script: /opt/CAPEv2/cape2.sh base cape 
      # args:
        # executable: bash


    - name: Change ownership of /opt/CAPEv2 to user cape and group cape
      file:
        path: /opt/CAPEv2
        state: directory
        recurse: yes
        owner: cape
        group: cape

    - name: Debug CAPE installation output
      debug:
        var: cape_install_output


    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    # Remove after
    # - name: Remove temporary GPG key file
    #   file:
    #     path: /tmp/RPM-GPG-KEY-mysql
    #     state: absent
