- name: Creates A new storage pool and host-only-network
  hosts: localhost
  become: yes
  
  tasks:
    - name: Create a directory to store .qcow2 file if it does not exist
      become: yes
      # shell: >
      #   mkdir -p /data1/libvirt/images
      file:
          path: /data1/libvirt/images/
          state: directory
          mode: '0755'
    
    # - name: Change the directory to writable
    #   become: yes
    #   shell: >
    #     chmod +w /data1/libvirt/images
    - name: Create the new default storage pool
      become: yes
      command: "{{ item }}"
      loop:
        - virsh pool-define-as default dir --target "/data1/libvirt/images"
        - virsh pool-build default
        - virsh pool-start default
        - virsh pool-autostart default

    
      