---
#  Be sure to create a inventory.ini with [cape] and an IP for the cape server  
# You need to install sshpass - 
#  ansible-playbook -i inventory.ini playbook_cape_v2.yaml --ask-become-pass
- name: CAPE Deployment
  hosts: cape
  become: yes
  tasks:
    - name: Update and install dependencies for git
      apt:
        name: git
        state: present
        force_apt_get: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: yes  # This allows the playbook to continue if the task fails


    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Ensure Python 3 pip is installed
      apt:
        name: python3-pip
        state: present
        force_apt_get: yes 
      ignore_errors: yes  # This allows the playbook to continue if the task fails

    - name: Install Poetry using pip
      pip:
        name: poetry
        executable: pip3
      ignore_errors: yes  # This allows the playbook to continue if the task fails
        

#  The part for CAPE related install
    - name: Add CAPE directory as a safe Git directory
      command: git config --global --add safe.directory /opt/CAPEv2

    - name: Clone CAPE repository
      git:
        repo: https://github.com/kevoreilly/CAPEv2.git
        dest: /opt/CAPEv2
        version: fa94c917659a24a412ae793a54e2be48e5f15ec7
        force: no  # Ensure it doesn't overwrite or force changes
      ignore_errors: yes  # This allows the playbook to continue if the task fails


    - name: Check if CAPEv2 repo already exists
      stat:
        path: /opt/CAPEv2/.git
      register: cape_repo_exists

    - name: Skip cloning if repository already exists
      git:
        repo: https://github.com/kevoreilly/CAPEv2.git
        dest: /opt/CAPEv2
        version: fa94c917659a24a412ae793a54e2be48e5f15ec7
      when: not cape_repo_exists.stat.exists
      ignore_errors: yes

    - name: Install CAPE dependencies
      pip:
        requirements: /opt/CAPEv2/requirements.txt
      ignore_errors: yes

    - name: Copy CAPE installation script from local to remote
      copy:
        src: ./cape2.sh
        dest: /opt/CAPEv2/cape2.sh
        mode: '0755'

    - name: Pre-configure debconf for wireshark-common
      debconf:
        name: "wireshark-common"
        question: "wireshark-common/install-setuid"
        value: "true"
        vtype: "boolean"
        
    - name: Run CAPE installation script after releasing lock
      shell: |
          DEBIAN_FRONTEND=noninteractive yes "y" | sudo bash /opt/CAPEv2/cape2.sh base cape
      become: yes
      register: cape_install_output
      retries: 5
      delay: 30
      until: cape_install_output.rc == 0
  

    - name: Change ownership of /opt/CAPEv2 to user cape and group cape
      file:
        path: /opt/CAPEv2
        state: directory
        recurse: yes
        owner: cape
        group: cape

    - name: Debug CAPE installation output
      debug:
        var: cape_install_output

# Copy our updated Config scripts from https://github.com/Cassandra-Fu/CAPE_SIT_EDITION
    - name: Replace cuckoo.conf file with our updated one
      copy:
          src: ./conf/cuckoo.conf
          dest: /opt/CAPEv2/cuckoo.conf
          mode: '0644'
    
    - name: Replace auxiliary.conf file with our updated one
      copy:
          src: ./conf/auxiliary.conf
          dest: /opt/CAPEv2/auxiliary.conf
          mode: '0644'

    - name: Replace reporting.conf file with our updated one
      copy:
          src: ./conf/reporting.conf
          dest: /opt/CAPEv2/reporting.conf
          mode: '0644'

    - name: Replace routing.conf file with our updated one
      copy:
          src: ./conf/routing.conf
          dest: /opt/CAPEv2/routing.conf
          mode: '0644'

    - name: Replace web.conf file with our updated one
      copy:
          src: ./conf/web.conf
          dest: /opt/CAPEv2/web.conf
          mode: '0644'
    - name: Replace web.conf file with our updated one
      copy:
          src: ./conf/cuckoo.conf
          dest: /opt/CAPEv2/cuckoo.conf
          mode: '0644'

    - name: Install poetry dependencies in CAPEv2 directory
      shell: |
        cd /opt/CAPEv2
        poetry install
      args:
        chdir: /opt/CAPEv2  # Ensures the command is executed in this directory
      become: yes
      ignore_errors: yes  # This allows the playbook to continue if the task fails

    - name: Add CAPE python path
      shell: |
        echo "export PYTHONPATH=/opt/CAPEv2:\$PYTHONPATH" >> ~/.bashrc

    - name: INSTALL FLARE Signatures
      shell: |
        cd /opt/CAPEv2/utils
        python3 /opt/CAPEv2/utils/community.py -cr
      args:
        chdir: /opt/CAPEv2/utils  # Ensures the command is executed in this directory
      become: yes
      ignore_errors: yes  # This allows the playbook to continue if the task fails

    - name: Run Django migrations for CAPE as the cape user
      shell: |
        python3 manage.py migrate
      become: yes
      become_user: cape  # Run as the non-root cape user (adjust if needed)
      args:
        chdir: /opt/CAPEv2/web  # Ensures the command is executed in this directory
    
    - name: Install Missing flare-floss dependencies
      shell: |
        cd /opt/CAPEv2/web
        poetry run pip install -U flare-floss
      args:
        chdir: /opt/CAPEv2/web  # Ensures the command is executed in this directory

# Create super user in cape
    - name: Run createsuperuser command with automated responses
      expect:
        command: python3 /opt/CAPEv2/web/manage.py createsuperuser
        chdir: /opt/CAPEv2/web
        responses:
          "Username": "cape\n"
          "Email address": "cape@example.com\n"
          "Password": "cape_pass\n"
          "Password (again)": "cape_pass\n"
      ignore_errors: yes
      become: yes
      become_user: cape

      # no_log: true  # hides the password and other sensitive info in the output


    - name: Generate API token
      shell: |
        python3 /opt/CAPEv2/web/manage.py drf_create_token cape
      args:
        chdir: /opt/CAPEv2/web  # Ensures the command is executed in this directory
      register: command_output
      become: no
  
    - name: Extract token from command output
      set_fact:
        extracted_token: "{{ command_output.stdout | regex_search('generated token (.*) for user cape') | regex_replace('generated token ', '') }}"
  
    - name: Save extracted token to a file on the remote host
      copy:
        content: "{{ extracted_token }}"
        dest: "/tmp/extracted_token.txt"
  
    - name: Fetch the extracted token file to the local machine
      fetch:
        src: "/tmp/extracted_token.txt"
        dest: "./local_extracted_token.txt"
        flat: yes

    # Install GUI for Ubuntu

    - name: Find the process holding the lock on /var/lib/dpkg/lock-frontend
      shell: lsof -t /var/lib/dpkg/lock-frontend
      register: lock_holder_pid
      ignore_errors: yes  # In case there’s no process holding the lock
      failed_when: lock_holder_pid.rc != 0 and lock_holder_pid.stdout != ""  # Only fail if there's output with a non-zero return code

    - name: Kill the lock holder process
      shell: kill -9 {{ lock_holder_pid.stdout }}
      when: lock_holder_pid.stdout is defined and lock_holder_pid.stdout != ""
      ignore_errors: yes

      
    - name: Preconfigure debconf for slim as default display manager
      debconf:
        name: "slim"
        question: "shared/default-x-display-manager"
        value: "slim"
        vtype: "select"

    - name: Install slim display manager
      shell: yes "y" | apt-get install -y slim
      ignore_errors: yes

    - name: Install ubuntu-desktop-minimal with slim preselected
      shell: DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop-minimal
      ignore_errors: yes

    - name: Start slim display manager
      shell: service slim start
      ignore_errors: yes
    
# Cleanup
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
